version: "3.3"

services:
  backend:
    build:
      context: ../go-backend/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DOCKER_MODE=1
    ports:
      - "8082:8082"

#  postgres:
#    image: postgres:latest
#    restart: always
#    env_file:
#      - ../go-backend/.env
#    ports:
#      - "5434:5434"
